/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

/**
 *
 * @author perpustakaan
 */
public class DlgAbout extends javax.swing.JDialog {

    
    public DlgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(465,515);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel6 = new javax.swing.JLabel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        BtnKeluar = new widget.Button();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ About Program ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setForeground(new java.awt.Color(102, 204, 255));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(50, 50, 50));
        jLabel6.setText(".: Aplikasi ");
        jLabel6.setName("jLabel6"); // NOI18N
        internalFrame1.add(jLabel6);
        jLabel6.setBounds(10, 18, 90, 20);

        panelGlass1.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass1.setOpaqueImage(false);
        panelGlass1.setRound(false);
        panelGlass1.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(50, 50, 50));
        jLabel31.setText("Aplikasi ini dikembangkan oleh Khanza Soft Media dan dimodifikasi");
        jLabel31.setName("jLabel31"); // NOI18N
        panelGlass1.add(jLabel31);
        jLabel31.setBounds(10, 30, 430, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(50, 50, 50));
        jLabel37.setText("SIMRS Khanza UPDATE 2026");
        jLabel37.setName("jLabel37"); // NOI18N
        panelGlass1.add(jLabel37);
        jLabel37.setBounds(10, 10, 430, 20);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(50, 50, 50));
        jLabel38.setText(" oleh IT RS Bhayangkara Batam");
        jLabel38.setName("jLabel38"); // NOI18N
        panelGlass1.add(jLabel38);
        jLabel38.setBounds(8, 50, 420, 14);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(50, 50, 50));
        jLabel39.setText("Dilarang Keras Memperjual/Belikan Aplikasi SIMRS Khanza tanpa seijin Pengembang");
        jLabel39.setName("jLabel39"); // NOI18N
        panelGlass1.add(jLabel39);
        jLabel39.setBounds(10, 70, 420, 14);

        internalFrame1.add(panelGlass1);
        panelGlass1.setBounds(7, 38, 590, 90);

        panelGlass4.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass4.setOpaqueImage(false);
        panelGlass4.setRound(false);
        panelGlass4.setLayout(null);

        panelGlass5.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass5.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/menu.png"))); // NOI18N
        panelGlass5.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass5.setRound(false);
        panelGlass5.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass5.setLayout(null);
        panelGlass4.add(panelGlass5);
        panelGlass5.setBounds(10, 20, 30, 30);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Close");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass4.add(BtnKeluar);
        BtnKeluar.setBounds(480, 130, 100, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(50, 50, 50));
        jLabel36.setText("RUMAH SAKIT BHAYANGKARA BATAM POLDA KEPRI");
        jLabel36.setName("jLabel36"); // NOI18N
        panelGlass4.add(jLabel36);
        jLabel36.setBounds(50, 20, 420, 15);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(50, 50, 50));
        jLabel40.setText("Jln. Dang Merdu KM2 Kecamatan Nongsa, Kelurahan Batu Besar");
        jLabel40.setName("jLabel40"); // NOI18N
        panelGlass4.add(jLabel40);
        jLabel40.setBounds(50, 35, 420, 14);

        panelGlass6.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass6.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wa.png"))); // NOI18N
        panelGlass6.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass6.setRound(false);
        panelGlass6.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass6.setLayout(null);
        panelGlass4.add(panelGlass6);
        panelGlass6.setBounds(10, 60, 30, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(50, 50, 50));
        jLabel41.setText("INFO LEBIH LANJUT HUBUNGI");
        jLabel41.setName("jLabel41"); // NOI18N
        panelGlass4.add(jLabel41);
        jLabel41.setBounds(50, 60, 420, 15);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(50, 50, 50));
        jLabel42.setText("No Telp/Whatsapp 085371042445");
        jLabel42.setName("jLabel42"); // NOI18N
        panelGlass4.add(jLabel42);
        jLabel42.setBounds(50, 80, 420, 14);

        internalFrame1.add(panelGlass4);
        panelGlass4.setBounds(7, 155, 590, 170);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);
        internalFrame1.getAccessibleContext().setAccessibleName("::[ Tentang Aplikasi ]::");
        internalFrame1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
}//GEN-LAST:event_BtnKeluarKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgAbout dialog = new DlgAbout(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel6;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    // End of variables declaration//GEN-END:variables

}
